const products = [
    {
        id: 1,
        image_Url: "catalog-images/image1.jpg",
        title: "SG48, ½d rose-red plate 20, NH MINT. Cat £350. SJ ",
        price: 39.99,
        currency_icon: "£",
        currency: "Euro",
        description: "4 days, 0h",
        category: "",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 2,
        image_Url: "catalog-images/image2.jpg",
        title: "#9 Used, F-VF, Clean and attractive, very light cancel (CV $100 - ID25462)",
        price: 43.99,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 3,
        image_Url: "catalog-images/image3.jpg",
        title: "#10 Used, Nearly 4 margins (CV $190 - ID29057)",
        price: 57.50,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 4h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 4,
        image_Url: "catalog-images/image4.jpg",
        title: " USA 1857 Scott #25 VF, Used. Light cancel. Choice stamp. Cat $180.",
        price: 79.99,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 4h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 5,
        image_Url: "catalog-images/image5.jpg",
        title: "#36 Used, Fine, Sound (CV $300 - ID19114)",
        price: 62.50,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 6,
        image_Url: "catalog-images/image6.jpg",
        title: "United States (Us) 65 Mint VF NH, Block of 4. Scarce as Such",
        price: 879.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 7,
        image_Url: "catalog-images/image7.jpg",
        title: "United States (Us) 67 Used F-Vf Light Cancel With PFC ",
        price: 519.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 8,
        image_Url: "catalog-images/image8.jpg",
        title: " USA 1862 Scott #70 Used. Bullseye cancel. Very Fresh. Catalog $300 ",
        price: 87.50,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 9,
        image_Url: "catalog-images/image9.jpg",
        title: "#70 Used, Ave-F, Nice blue cancel, clean (CV $300 - ID28749)",
        price: 48.50,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 10,
        image_Url: "catalog-images/image10.jpg",
        title: "USA 1861 Scott #72 Used. Sealed tear. Nice cancel. Catalog $600.00",
        price: 97.50,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 11,
        image_Url: "catalog-images/image11.jpg",
        title: "United States (Us) 75 Used, Fine, Light Cancel, RED Brown",
        price: 157.50,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 12,
        image_Url: "catalog-images/image12.jpg",
        title: "United States (Us) 78 Used F-Vf 24c Washington",
        price: 95.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 13,
        image_Url: "catalog-images/image13.jpg",
        title: " USA 1863 Scott #78 Used. Light cancel. Nice perforations. Cat $350",
        price: 75.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 14,
        image_Url: "catalog-images/image14.jpg",
        title: " USA 1862 Scott #78 Used. Sound. Light cancel. Catalog $400.00. ",
        price: 75.99,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 15,
        image_Url: "catalog-images/image15.jpg",
        title: "78a F-VF used neat cancel with nice color cv $ 425 ! see pic ! ",
        price: 65.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 16,
        image_Url: "catalog-images/image16.jpg",
        title: "Edw 1949 vender: EE. UU. 1862 Scott #78a gris lila. usado. PSAG certificado. Cat $425. ",
        price: 97.50,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 17,
        image_Url: "catalog-images/image17.jpg",
        title: "87 Fine F-grill used neatface free cancel with nice color cv $ 200 ! see pic ! ",
        price: 95.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 18,
        image_Url: "catalog-images/image18.jpg",
        title: "#89 Mint OG, Ave-F, Rare (CV $5000 - ID25174)",
        price: 609.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 19,
        image_Url: "catalog-images/image19.jpg",
        title: "90 F-VF F-grill used neat light cancel with nice color cv $ 375 ! see pic ! ",
        price: 95.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 20,
        image_Url: "catalog-images/image20.jpg",
        title: "92 F-VF F-grill used neat light cancel with nice color cv $ 425 ! see pic ! ",
        price: 87.50,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    },
]