const products = [
    {
        id: 1,
        image_Url: "catalog-images/image1.jpg",
        title: "SG48, ½d rose-red plate 20, NH MINT. Cat £350. SJ ",
        price: 39.99,
        currency_icon: "£",
        currency: "Euro",
        description: "4 days, 0h",
        category: "",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 2,
        image_Url: "catalog-images/image2.jpg",
        title: "#9 Used, F-VF, Clean and attractive, very light cancel (CV $100 - ID25462)",
        price: 43.99,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 3,
        image_Url: "catalog-images/image3.jpg",
        title: "Scott #O73 - F - 2c Brown - Treasury - Part OG - HR - 1873",
        price: 30.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 4h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 4,
        image_Url: "catalog-images/image4.jpg",
        title: " Scott #RE40 - 18c Green - Cordials, Wines, Etc. Stamps - Unused - 1916",
        price: 15.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 4h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 5,
        image_Url: "catalog-images/image5.jpg",
        title: "U.S. 560 M-HM SINGLE AS SHOWN (V5015)",
        price: 9.34,
        currency_icon: "$",
        currency: "dolor",
        description: "3h 27m",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 6,
        image_Url: "catalog-images/image6.jpg",
        title: "United States (Us) 65 Mint VF NH, Block of 4. Scarce as Such",
        price: 879.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 7,
        image_Url: "catalog-images/image7.jpg",
        title: "US Scott #232 - F/VF - 3c Colubmus Santa Maria - Green - MNH - 1893",
        price: 57.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 8,
        image_Url: "catalog-images/image8.jpg",
        title: "US Stamps # 209 MLH VF Disturbed OG Scott Value $160.00",
        price: 87.50,
        currency_icon: "$",
        currency: "dolor",
        description: "22h 51m",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 9,
        image_Url: "catalog-images/image9.jpg",
        title: "US Stamps # 566 MNH Superb",
        price: 50.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 10,
        image_Url: "catalog-images/image10.jpg",
        title: "US Stamps # 566 MNH Superb",
        price: 17.44,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 11,
        image_Url: "catalog-images/image11.jpg",
        title: "622 VF/XF OG NH, Nice Deep Color! g7356",
        price: 52.47,
        currency_icon: "$",
        currency: "dolor",
        description: "3h  40m",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 12,
        image_Url: "catalog-images/image12.jpg",
        title: "U.S. #120 PROOF",
        price: 45.00,
        currency_icon: "$",
        currency: "dolor",
        description: "5 days, 8h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 13,
        image_Url: "catalog-images/image13.jpg",
        title: "O23s F/VF mint NH, NGAI, Specimen Overprint, ..MORE.. b4618",
        price: 1633.50,
        currency_icon: "$",
        currency: "dolor",
        description: "2 days, 12h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 14,
        image_Url: "catalog-images/image14.jpg",
        title: " USA 1862 Scott #78 Used. Sound. Light cancel. Catalog $400.00. ",
        price: 75.99,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 15,
        image_Url: "catalog-images/image15.jpg",
        title: "566 XF-SUPERB OG NH, w/PSE (GRADED 95 (10/07)..MORE.. g4877",
        price: 242.55,
        currency_icon: "$",
        currency: "dolor",
        description: "3h , 40m",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 16,
        image_Url: "catalog-images/image16.jpg",
        title: "325 MINT FVF OG NH Cat $170",
        price: 6.50,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 17,
        image_Url: "catalog-images/image17.jpg",
        title: "US STAMPS #281-284 MINT OG H LOT #72432*",
        price: 213.75,
        currency_icon: "$",
        currency: "dolor",
        description: "9h 40m",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 18,
        image_Url: "catalog-images/image18.jpg",
        title: "#89 Mint OG, Ave-F, Rare (CV $5000 - ID25174)",
        price: 609.00,
        currency_icon: "$",
        currency: "dolor",
        description: "1 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 19,
        image_Url: "catalog-images/image19.jpg",
        title: "U.S. 1904-13 COMM. 323 Mint (ID # 78470)",
        price: 45.00,
        currency_icon: "$",
        currency: "dolor",
        description: "10h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 20,
        image_Url: "catalog-images/image20.jpg",
        title: "US Sc PR112 MLH. 1895 $50 dull rose 'Commerce' Newspaper stamp, CERT",
        price: 1575.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 21,
        image_Url: "catalog-images/image21.jpg",
        title: "US Stamp #929 Iwo Jima 3c, PSE Cert - SUPERB 98 - Mint OGNH - SMQ $150.00",
        price: 150.00,
        currency_icon: "$",
        currency: "dolor",
        description: "5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    },
    {
        id: 22,
        image_Url: "catalog-images/image22.jpg",
        title: "US Stamp #795 Ordinance of 1787 3c - PSE Cert - SUPERB 98 - MNH - SMQ $140.00",
        price: 140.00,
        currency_icon: "$",
        currency: "dolor",
        description: "3 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 23,
        image_Url: "catalog-images/image23.jpg",
        title: "US Stamp #1184 George W. Norris 4c, PSE Cert - GEM 100 - MOGNH - SMQ $170.00",
        price: 170.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 1h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    }, {
        id: 24,
        image_Url: "catalog-images/image24.jpg",
        title: "Scott #JQ2 Mint-NH Postage Due Stamp! Very Nice! Low Start, SCV $190",
        price: 115.00,
        currency_icon: "$",
        currency: "dolor",
        description: "4 days, 5h",
        category: "United state",
        badges: "",
        Creators:"Douglas Gordons"
    },
]